"""adding ccontent column

Revision ID: 0f8b3a1fac08
Revises: 22a076c18845
Create Date: 2024-03-23 17:46:14.255040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8b3a1fac08'
down_revision: Union[str, None] = '22a076c18845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.String(), nullable=False))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###
